# This workflow will perform a test whenever there
# is some change in code done to ensure that the changes
# are not buggy and we are getting the desired output.
name: Build from dockerfile
on: [push, pull_request, workflow_dispatch]
env:
  IMAGE_NAME: "hello-world"

jobs:
  build:
    name: Build image using Buildah
    runs-on: ubuntu-20.04
    steps:

      # Checkout buildah action github repository
      - name: Checkout Buildah action
        uses: actions/checkout@v2
        with:
          path: "buildah-build"

      - name: Create Dockerfile
        run: |
          cat > Dockerfile<<EOF
          FROM busybox
          RUN echo "hello world"
          EOF

      # Build image using Buildah action
      - name: Build Image
        id: build_image
        uses: ./buildah-build/
        with:
          image: ${{ env.IMAGE_NAME }}
          layers: false
          tags: 'latest ${{ github.sha }}'
          dockerfiles: |
            ./Dockerfile

      - name: Echo Outputs
        run: |
          echo "Image: ${{ steps.build_image.outputs.image }}"
          echo "Tags: ${{ steps.build_image.outputs.tags }}"

      # Check if image is build
      - name: Check images created
        run: buildah images | grep '${{ env.IMAGE_NAME }}'
